### ISSUE TITLE
Admin and Interviewer Passwords

### ISSUE THREAD

**Issue by mustafatalha** [vsaraminev/ApplicantsSystem#4]
1 admin(admin@mysite.com) and 1 interviewer(interviewer@mysite.com) accounts exist in database, but password are encrypted. Register form isn't working. So I couldn't enter the app :D 

Can u share account passwords ?

**Comment by igdragoev** [comment]
Password for Armin account is currently hardcoded. See here https://github.com/vsaraminev/ApplicantsSystem/blob/144cb625390a2f47c5cb4291a158967eb6bacee8/ApplicantsSystem.Web/Infrastructure/ApplicationBuilderExtensions.cs

It is admin123
